local A, L = ...
local _, core = ...;

local LSM = LibStub('LibSharedMedia-3.0')
local fontpath = "Interface\\Addons\\"..A.."\\fonts\\"

core.Fonts = {}; -- adds Fonts table to addon namespace
local Fonts = core.Fonts

-- Register Fonts
if LSM then	
	LSM:Register("font", "Ace Futurism", fontpath .. "Ace_Futurism.ttf")
	LSM:Register("font", "ExpressWay", fontpath .. "expressway.ttf")
	LSM:Register("font", "PT Sans", fontpath .. "PT_Sans-Web-Regular.ttf")
	LSM:Register("font", "PT Sans Bold", fontpath .. "PT_Sans-Web-Bold.ttf")
	LSM:Register("font", "PT Sans Bold Italic", fontpath .. "PT_Sans-Web-BoldItalic.ttf")
	LSM:Register("font", "PT Sans Italic", fontpath .. "PT_Sans-Web-Italic.ttf")
	LSM:Register("font", "Carlito", fontpath .. "Carlito-Regular.ttf")
	LSM:Register("font", "Carlito Bold", fontpath .. "Carlito-Bold.ttf")
	LSM:Register("font", "Carlito Italic", fontpath .. "Carlito-Italic.ttf")
	LSM:Register("font", "Carlito Bold Italic", fontpath .. "Carlito-BoldItalic.ttf")
	LSM:Register("font", "Ubuntu", fontpath .. "Ubuntu-R.ttf")
	LSM:Register("font", "Ubuntu Italic", fontpath .. "Ubuntu-RI.ttf")
	LSM:Register("font", "Ubuntu Condensed", fontpath .. "Ubuntu-C.ttf")
	LSM:Register("font", "Ubuntu Bold", fontpath .. "Ubuntu-B.ttf")
	LSM:Register("font", "Ubuntu Bold Italic", fontpath .. "Ubuntu-BI.ttf")
	LSM:Register("font", "Ubuntu Light", fontpath .. "Ubuntu-L.ttf")	
	LSM:Register("font", "Ubuntu Light Italic", fontpath .. "Ubuntu-LI.ttf")
	LSM:Register("font", "Ubuntu Medium", fontpath .. "Ubuntu-M.ttf")	
	LSM:Register("font", "Ubuntu Medium Italic", fontpath .. "Ubuntu-MI.ttf")
	LSM:Register("font", "Ubuntu Mono", fontpath .. "UbuntuMono-R.ttf")
	LSM:Register("font", "Ubuntu Mono Italic", fontpath .. "UbuntuMono-RI.ttf")
	LSM:Register("font", "Ubuntu Mono Bold", fontpath .. "UbuntuMono-B.ttf")
	LSM:Register("font", "Ubuntu Mono Bold Italic", fontpath .. "UbuntuMono-BI.ttf")
	LSM:Register("font", "ComicNeue", fontpath .. "ComicNeue-Regular.ttf")	
	LSM:Register("font", "ComicNeue Light", fontpath .. "ComicNeue-Light.ttf")	
	LSM:Register("font", "ComicNeue Bold", fontpath .. "ComicNeue-Bold.ttf")	
	LSM:Register("font", "Candara", fontpath .. "Candara.ttf")
	LSM:Register("font", "Candara Bold", fontpath .. "Candarab.ttf")
	LSM:Register("font", "Candara Italic", fontpath .. "Candarai.ttf")
	LSM:Register("font", "Candara Bold Italic", fontpath .. "Candaraz.ttf")
	LSM:Register("font", "Verdana", fontpath .. "Verdana.TTF")
	LSM:Register("font", "Verdana Bold", fontpath .. "Verdanab.TTF")
	LSM:Register("font", "Verdana Italic", fontpath .. "Verdanai.TTF")
	LSM:Register("font", "Verdana Bold Italic", fontpath .. "Verdanaz.TTF")
	LSM:Register("font", "Lauren", fontpath .. "lauren-normal.ttf")
	LSM:Register("font", "Lauren Bold", fontpath .. "lauren-bold.ttf")
	LSM:Register("font", "Lauren Italic", fontpath .. "lauren-italic.ttf")
	LSM:Register("font", "Lauren Bold Italic", fontpath .. "lauren-bold-italic.ttf")
	LSM:Register("font", "Lato", fontpath .. "Lato-Regular.ttf")
	LSM:Register("font", "Lato Bold", fontpath .. "Lato-Bold.ttf")
	LSM:Register("font", "Lato Italic", fontpath .. "Lato-Italic.ttf")
	LSM:Register("font", "Lato Bold Italic", fontpath .. "Lato-BoldItalic.ttf")
	LSM:Register("font", "Lato Thin", fontpath .. "Lato-Thin.ttf") 
	LSM:Register("font", "Happy Giraffe", fontpath .. "The Happy Giraffe Demo.ttf")
	LSM:Register("font", "Lady Bug", fontpath .. "Ladybug Love Demo.ttf")
	LSM:Register("font", "Droid Sans Mono", fontpath .. "DroidSansMono.ttf")
	LSM:Register("font", "Droid Sans", fontpath .. "DroidSans-Regular.ttf")
	LSM:Register("font", "Droid Sans Bold", fontpath .. "DroidSans-Bold.ttf")	
	LSM:Register("font", "AD Mono", fontpath .. "a_d_mono.ttf")
	LSM:Register("font", "Terminus", fontpath .. "Terminus.ttf")
	LSM:Register("font", "Terminus Bold", fontpath .. "TerminusBold.ttf")
	LSM:Register("font", "Ropa Sans", fontpath .. "RopaSans-Regular.ttf")
	LSM:Register("font", "Dosis", fontpath .. "Dosis-Regular.ttf")
	LSM:Register("font", "Dosis SemiBold", fontpath .. "Dosis-SemiBold.ttf")
	LSM:Register("font", "Dosis Bold", fontpath .. "Dosis-Bold.ttf")
	LSM:Register("font", "Dosis Medium", fontpath .. "Dosis-Medium.ttf")
	LSM:Register("font", "Noto Sans", fontpath .. "NotoSans-Regular.ttf")
	LSM:Register("font", "Noto Sans Bold", fontpath .. "NotoSans-Bold.ttf")
	LSM:Register("font", "Noto Sans Italic", fontpath .. "NotoSans-Italic.ttf")
	LSM:Register("font", "Noto Sans Bold Italic", fontpath .. "NotoSans-BoldItalic.ttf")
	LSM:Register("font", "Noto", fontpath .. "NotoSerif-Regular.ttf")
	LSM:Register("font", "Noto Bold", fontpath .. "NotoSerif-Bold.ttf")
	LSM:Register("font", "Noto Italic", fontpath .. "NotoSerif-Italic.ttf")
	LSM:Register("font", "Noto Bold Italic", fontpath .. "NotoSerif-BoldItalic.ttf")
	LSM:Register("font", "Noto Mono", fontpath .. "NotoMono-Regular.ttf")
	LSM:Register("font", "Roboto", fontpath .. "Roboto-Regular.ttf")
	LSM:Register("font", "Roboto Bold", fontpath .. "Roboto-Bold.ttf")
	LSM:Register("font", "Roboto Italic", fontpath .. "Roboto-Italic.ttf")
	LSM:Register("font", "Roboto Bold Italic", fontpath .. "Roboto-BoldItalic.ttf")
end

local lsmfonts = LSM:List("font")

function Fonts:GetAllFonts()
	return lsmfonts
end